---
title: "719_Lab_1"
author: "Nicholas Lichtsinn"
date: "4/11/2022"
output: html_document
---

```{r}
# creating a pie chart
pie(c(7,4,2,12))
# assigning vector to a value
x <- c(7,6,7.2,12)
# creating pie chart from x
pie(x)
```
```{r}
# adding title and color to the plot
pie(x, main = "Nick's Pie", col = c("red", "orange", "tan", "yellow"))
```

```{r}
# adding labels to the plot
pie(x
    , main = "Nick's Pie"
    , col = c("red", "orange", "tan", "yellow")
    , labels = c("a", "b", "c", "d"))
```

```{r}
# creating a dot plot
plot(c(1,3,6,4), pch = 16, col = c("red", "orange", "tan", "yellow"), cex = 3)

```

```{r}
# creating random normally distributed set of data
x <- rnorm(n = 10)
#plotting x
plot(x)
```

```{r}
# adding to the plot
# changing to a line plot, default is "p" for point 
plot(x, type = "l")

# Creating histogram with wider lines, square edges and a color
plot(x, type = "h", lwd = 5, lend = 2, col = "purple")

```

```{r}
# adding a title and x & y labels
plot(x, type = "h", lwd = 5, lend = 2, col = "purple", main = "change in net worth", xlab = "time in years", ylab = "in millions")
```

```{r}
# bty gets rid of box around the plot
plot(x, type = "h", lwd = 5, lend = 2, col = "purple", main = "change in net worth", xlab = "time in years", ylab = "in millions"
     , bty = "n")
```

```{r}
# creating plot
# changing background to gray using parameters setting
par(bg = "gray")
plot(x, type = "h", lwd = 20, col = c("blue", "orange"), bty = "n", lend = 2)

```

```{r}
# creating variable n
n <- 27
# creating letters variable with subset of letters
my_letters <- sample(letters[1:3], size = n, replace = T)

```

```{r}
# creating a table for my_letters
tab <- table(my_letters)

# creating a barplot for my_letters table
barplot(tab, col = c("red", "tan", "orange"), names.arg = c("sales", "ops", "it"), border = "white", xlab = "departments", ylab = "employees", main = "Company Employees", horiz = TRUE, las = 1, density = 20, angle = c(45, 90, 12))
```

```{r}
# x with 1000 obs, mean of 10 and standard deviation of 1
x <- rnorm(n = 1000, mean = 10, sd = 1)
# creating histogram
hist(x, main = "what is the distribution of x")
# creating boxplot
boxplot(x, horizontal = T)
```

```{r}
# creating plot with log normal dist, skewed with most observations low and a few high
x <- rlnorm(n = 1000, meanlog = 1, sdlog = 1)

# using parameter mfrow to break space up into x rows and columns and put both plots on the same space
par(mfrow = c(2, 1))
hist(x)
boxplot(x, horizontal = T)

```

```{r}
# using function log10 to take the log of all values in x to create a normal distribution
hist(log10(x))

```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```

```{r}


```